'use server';

/**
 * @fileOverview An AI-powered symptom checker flow.
 *
 * - aiSymptomChecker - A function that takes symptoms as input and returns possible causes.
 * - AISymptomCheckerInput - The input type for the aiSymptomChecker function.
 * - AISymptomCheckerOutput - The return type for the aiSymptomChecker function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AISymptomCheckerInputSchema = z.object({
  symptoms: z
    .string()
    .describe('The symptoms experienced by the user, described in detail.'),
  medicalHistory: z
    .string()
    .optional()
    .describe('The user medical history, including known diagnoses and prescriptions.'),
});
export type AISymptomCheckerInput = z.infer<typeof AISymptomCheckerInputSchema>;

const AISymptomCheckerOutputSchema = z.object({
  possibleCauses: z
    .string()
    .describe('Possible causes of the symptoms, generated by AI.'),
});
export type AISymptomCheckerOutput = z.infer<typeof AISymptomCheckerOutputSchema>;

export async function aiSymptomChecker(input: AISymptomCheckerInput): Promise<AISymptomCheckerOutput> {
  return aiSymptomCheckerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiSymptomCheckerPrompt',
  input: {schema: AISymptomCheckerInputSchema},
  output: {schema: AISymptomCheckerOutputSchema},
  prompt: `You are an AI-powered symptom checker that analyzes user-provided symptoms and medical history to suggest possible causes.

  Symptoms: {{{symptoms}}}
  Medical History: {{{medicalHistory}}}

  Based on the provided symptoms and medical history, generate a list of possible causes. Be as detailed as possible.
  Please remember that this is not a substitute for professional medical advice.
  `,
});

const aiSymptomCheckerFlow = ai.defineFlow(
  {
    name: 'aiSymptomCheckerFlow',
    inputSchema: AISymptomCheckerInputSchema,
    outputSchema: AISymptomCheckerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
