'use server';

/**
 * @fileOverview An AI-powered symptom checker flow that can analyze images.
 *
 * - aiSymptomChecker - A function that takes symptoms and an optional image and returns possible causes.
 * - AISymptomCheckerInput - The input type for the aiSymptomChecker function.
 * - AISymptomCheckerOutput - The return type for the aiSymptomChecker function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AISymptomCheckerInputSchema = z.object({
  symptoms: z
    .string()
    .describe('The symptoms experienced by the user, described in detail.'),
  medicalHistory: z
    .string()
    .optional()
    .describe('The user medical history, including known diagnoses and prescriptions.'),
  symptomImageDataUri: z
    .string()
    .optional()
    .describe(
      "An optional photo of the symptom (e.g. a skin rash) or a medical report, as a data URI. Format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AISymptomCheckerInput = z.infer<typeof AISymptomCheckerInputSchema>;

const AISymptomCheckerOutputSchema = z.object({
  possibleCauses: z
    .string()
    .describe('A detailed analysis and list of possible causes for the symptoms, generated by AI. This should be formatted as markdown.'),
});
export type AISymptomCheckerOutput = z.infer<typeof AISymptomCheckerOutputSchema>;

export async function aiSymptomChecker(input: AISymptomCheckerInput): Promise<AISymptomCheckerOutput> {
  return aiSymptomCheckerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiSymptomCheckerPrompt',
  input: {schema: AISymptomCheckerInputSchema},
  output: {schema: AISymptomCheckerOutputSchema},
  prompt: `You are an AI-powered symptom checker. Your role is to analyze user-provided symptoms, medical history, and an optional image to suggest possible causes and provide a detailed analysis.

  **IMPORTANT: You are not a doctor. Your analysis is for informational purposes only and is not a substitute for professional medical advice. Always include this disclaimer prominently at the end of your response.**

  Analyze the following information:

  **User's Described Symptoms:**
  {{{symptoms}}}

  **User's Medical History:**
  {{{medicalHistory}}}

  {{#if symptomImageDataUri}}
  **User-provided Image:**
  {{media url=symptomImageDataUri}}
  Analyze the image for any visual cues related to the symptoms. If it's a medical report, extract relevant information. If it's a physical symptom like a rash, describe what you see.
  {{/if}}

  **Your Task:**
  1.  Carefully review all provided information (text and image).
  2.  Generate a list of possible causes for the symptoms. For each cause, briefly explain why it might be relevant.
  3.  Provide a general analysis and suggest next steps, such as monitoring symptoms or consulting a specific type of doctor (e.g., a dermatologist for a skin issue).
  4.  Structure your response clearly using Markdown (headings, bullet points).
  5.  Conclude with the mandatory disclaimer.
  `,
});

const aiSymptomCheckerFlow = ai.defineFlow(
  {
    name: 'aiSymptomCheckerFlow',
    inputSchema: AISymptomCheckerInputSchema,
    outputSchema: AISymptomCheckerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
